FROM frolvlad/alpine-glibc

ADD ./envoy /

RUN chmod 777 /envoy 

ADD ./envoy.yaml /etc/

ADD ./lib/util.lua /lib/util.lua

CMD /envoy -l info -c /etc/envoy.yaml --service-node front-node --service-cluster front-cluster
