FROM frolvlad/alpine-glibc

RUN apk upgrade && apk add python3 && apk add curl
RUN python3 --version && pip3 --version
RUN pip3 install -q Flask==0.11.1 requests==2.18.4
RUN mkdir /code
ADD ./service.py /code
ADD ./start_service.sh /usr/local/bin/start_service.sh
RUN chmod u+x /usr/local/bin/start_service.sh

ADD ./service-envoy.yaml /etc/

ADD ./envoy /usr/local/bin/
RUN chmod u+x /usr/local/bin/envoy

ENTRYPOINT /usr/local/bin/start_service.sh
