FROM python:3.7

RUN python --version && pip --version
RUN pip install -q Flask==0.11.1 requests==2.18.4
RUN mkdir /code
ADD ./service.py /code
ADD ./start_service.sh /usr/local/bin/start_service.sh
RUN chmod u+x /usr/local/bin/start_service.sh

ADD ./service-envoy.yaml /etc/

ADD ./envoy /usr/local/bin/
RUN chmod u+x /usr/local/bin/envoy

ENTRYPOINT /usr/local/bin/start_service.sh
